name: presensi_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI Icons
  cupertino_icons: ^1.0.8
  hugeicons: ^1.0.2

  # Map dependencies (menggunakan Flutter Map + OpenStreetMap)
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  flutter_map_tile_caching: ^10.1.1

  flutter_image_compress: ^2.1.0  # Untuk kompress foto
  cached_network_image: ^3.3.1

  # Location services
  geolocator: ^14.0.2

  # Internationalization
  intl: ^0.20.2
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  path: ^1.9.0

  # State Management
  provider: ^6.1.1

  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_file_store: ^1.2.0

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4
  file_picker: ^10.3.3
  image_picker: ^1.1.2
  url_launcher: ^6.2.2
  open_filex: ^4.5.0

  connectivity_plus: ^6.1.4
  device_info_plus: ^9.1.1
  permission_handler: ^11.2.0
  safe_device: ^1.1.5 # Detect mock location, developer mode
  installed_apps: ^1.4.0 # Detect installed fake GPS apps

  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2
  device_preview: ^1.3.1
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/logo.png
    - assets/izin.webp
    - assets/lembur.webp
    - assets/shift.webp
    - assets/jadwal.webp
    - assets/informasi.webp
